### ISSUE TITLE
Использование mapActions

### ISSUE THREAD

**Issue by 7006** [GavrilenkoGeorgi/test-codebrightly#1]
```js
// внтури src/views/AllComments.vue
methods: {
    ...mapActions([
      `setAllComments`
    ]),
    deleteComment (id) {
      this.$store.dispatch(`deleteComment`, id)
    }
}
```
Это можно переписать в следующем виде 

```js
methods: {
    ...mapActions([
      `setAllComments`,
      'deleteComment'
    ])
}
```
Как это работает?

Пользователь нажимает на кнопку 
```html
<button
          class="comment-button"
          @click.prevent="deleteComment(comment.id)"
        >
          Delete
</button>
```
Выполняется обработчик события on-click - это метод deleteComment

Благодаря mapActions
```js
methods: {
    ...mapActions([
      'deleteComment'
    ])
}
```
Vuex добавляет новый метод в компонент. Это метод называется deleteComment и вызывает метод/действие (action) в хранилище (store) с таким же именем deleteComment

Если посмотреть на реализацию mapActions 

https://github.com/vuejs/vuex/blob/dev/src/helpers.js#L94 

То можно увидеть что там собственно и написано то что мы написали руками

```js
deleteComment (id) {
      this.$store.dispatch(`deleteComment`, id)
```

В сухом остатке - mapActions используется для того чтобы не писать код клей, единственной целью которого является запустить action из обработчика события пользовательского интерфейса

Ниже ссылка на документацию в которой более подробно/рельефно описана концепция store actions и инструментов для работы с ней

https://vuex.vuejs.org/ru/guide/actions.html

Соответсвенно, предложение состоит в том чтобы переписать фрагменты кода в проекте с использованием mapActions

**Comment by GavrilenkoGeorgi** [comment]
Да, спасибо! Попробую.

**Comment by 7006** [comment]
Можно изменения в коде оформить в виде pull request к этому issue. 

Вы умеете это делать?

**Comment by GavrilenkoGeorgi** [comment]
Не совсем. ( Буду рад советам, если у вас есть на них время.

**Comment by 7006** [comment]
https://www.youtube.com/playlist?list=PLDyvV36pndZHkDRik6kKF6gSb0N0W995h

Это серия уроков на русском языке о том как пользоваться системой контроля версий кода он же git

**Comment by 7006** [comment]
Давайте, Вы попробуйте сделать pull request с изменениями в коде которые обсуждались в этом issue. 

Когда закончим с этой задачей перейдем к следующей.

Если возникнут сложности не стесняйтесь пишите сюда alexbox86@gmail.com

**Comment by GavrilenkoGeorgi** [comment]
Хорошо, спасибо за помощь. В принципе всё понятно, осталось сделать. Если что, буду спрашивать.

**Comment by GavrilenkoGeorgi** [comment]
И ещё, этот `deleteComment`, насколько я понимаю, не единственное, что можно перенести в mapActions?

**Comment by 7006** [comment]
https://youtu.be/Wz7RDh6CylI вот скринкаст по тому как конкретно сделать pull request

У Кантора более фундаментальные вещи. Я бы рекомендовал посмотреть.

Собственно, пул реквест нужен для того чтобы другой разработчик мог понять какие именно изменения были сделаны. Какие строки были удалены , какие добавлены и тд.

**Comment by 7006** [comment]
Да, все места где компонент делает 

```js
this.$store.dispatch('fooBar', { ... })

```
Можно заменить на mapActions

**Comment by 7006** [comment]
Я вмержил пул реквест в мастер. Задачу выполнена.

**Comment by GavrilenkoGeorgi** [comment]
Спасибо за помощь, буду рад, если подскажете ещё какие-нибудь места в коде, которые можно переделать.
