### ISSUE TITLE
Разобраться с @click.prevent 

### ISSUE THREAD

**Issue by 7006** [GavrilenkoGeorgi/test-codebrightly#3]
```html
// внутри src/views/AllComments.vue
<button
          class="comment-button"
           @click.prevent="navToSingleComment(comment.id)"
        >
          Read more
</button>
```
Нужно отменять действие браузера по умолчанию там где это действительно необходимо.

Вот материал по этой теме -
https://learn.javascript.ru/default-browser-action

У кнопки есть атрибут type и в зависимости от его значения браузер совершает разные действия при нажатии на кнопку. 

Также стоит разобраться со случаем когда кнопка находится внутри формы и просто сама по себе. 

Вот тут более подробно освещена работа с формами. 
https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms

Собственно, предложение оставить @click.prevent там где это необходимо, в остальных убрать

**Comment by GavrilenkoGeorgi** [comment]
Pull request готов.

**Comment by 7006** [comment]
Замержил. 

В качестве закрепления материала рекомендую посмотреть в интернете ответ на вопрос "Какое значение по умолчанию у аттрибута type тэга button в разных браузерах?"

 P.S.
Вы сделали задачу согласно рекомендациям ведущих собаководов

**Comment by GavrilenkoGeorgi** [comment]
Если я правильно понял [stackoverflow](https://stackoverflow.com/questions/31644723/what-is-the-default-button-type): 
> If the button is within a form, the default behavior is submit.
> If the button is not within a form, it will do nothing.
[HTML <button> Tag](https://www.w3schools.com/tags/tag_button.asp)
> If your buttons are not to submit form data to a server, be sure to set their type attribute to button. Otherwise they will try to submit form data and to load the (nonexistent) response, possibly destroying the current state of the document.
[MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)
