### ISSUE TITLE
Вынести css  стили в собственные файлы

### ISSUE THREAD

**Issue by 7006** [GavrilenkoGeorgi/test-codebrightly#8]

**Comment by 7006** [comment]
https://github.com/GavrilenkoGeorgi/test-codebrightly/blob/7f7104c2d5911ddce3c06b61f73108036183eee4/src/views/SingleComment.vue#L51

Это появляется когда в файле были конфликты

То есть одну и ту же строчку изменили в разных ветках.

Просто оставляете тот код, который нужен. Остальное удаляете. Делаете пулреквест. Мержите.

**Comment by 7006** [comment]
Вообщем, теперь у Вас есть опыт большого пул реквеста. Когда в пул реквесте сделаны несколько задач. В это время в мастер зашли изменения по другой задаче и нужно актулизировать код в своей ветке.

Вообщем, это всегда проблематично. Поэтому лучше вливать небольшие атомарные изменения.

Я к тому, что это тоже полезный опыт

**Comment by GavrilenkoGeorgi** [comment]
Да ( Хорошо, что ничего серьёзного, типа тестовое задание, но действительно буду теперь знать как бывает.

**Comment by 7006** [comment]
На практике, Вы просто садитесь вместе с разработчиком чья ветка влилась в мастер первой и выбираете какие строки оставить какие удалить. 

Во всех ide есть понятный ui чтобы сделать это максимально безболезненно.

P.S. Дорогу осилит идущий. Не ошибается тот, кто ничего не делает.

**Comment by 7006** [comment]
https://help.github.com/en/articles/closing-issues-using-keywords

Можно в комментарии к мерж коммиту из ветки задачи в мастер вставить "секретное слово" и пул реквест закроет связанную с ним задачу
